---
# We install Cargo without apt because Debian's handling of cargo is different from the standard Rust management.
- name: Cargo
  vars:
    rustup_bin: "~/.cargo/bin/rustup"
  block:
    - name: Ensure rustup
      shell: |
        if [ ! -x "{{ rustup_bin }}" ]; then
          curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain stable
        fi
      args:
        creates: "{{ rustup_bin }}"

    - name: Update toolchain
      command: "{{ rustup_bin }} update stable"

    - name: Ensure cargo is in PATH
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line:    'export PATH="${HOME}/.cargo/bin:${PATH}"'
    - name: Pass cargo to other tasks
      set_fact:
        cargo_binary: "{{ ansible_env.HOME }}/.cargo/bin/cargo"

