---
- name: Update and upgrade
  apt:
    upgrade: full
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: ssh-client
  block:
    - name: Ensure directory exists
      file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
        mode: "0700"
    - name: SSH generic config
      blockinfile:
        path: "{{ ansible_user_dir }}/.ssh/config"
        marker: "# {mark} Generic config managed by Ansible"
        block: |
          AddKeysToAgent yes
          ForwardAgent yes
          StrictHostKeyChecking accept-new

- name: Set up editor
  block:
    - name: install neovim
      apt:
        name: neovim
      become: true

    - name: Set editor
      shell: update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 100
      become: true

    - name: Set editor env var
      become: true
      copy:
        content: |
          export EDITOR="/usr/bin/nvim"
        dest: /etc/profile.d/editor.sh

