---
- name: Update and upgrade
  apt:
    upgrade: full
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: ssh
  block:
    - name: ssh-agent
      tags: ["ssh-agent", "never"]
      block:
        - name: Ensure directory exists
          file:
            path: "{{ ansible_env.HOME }}/.config/systemd/user"
            state: directory
            mode: "0700"

        - name: Auto-start SSH-Agent
          copy:
            dest: "{{ ansible_env.HOME }}/.config/systemd/user/user-ssh-agent.service"
            mode: "0644"
            content: |
              [Unit]
              Description=SSH key agent

              [Service]
              Type=simple
              Environment=SSH_AUTH_SOCK=%t/ssh-agent.socket
              ExecStart=/usr/bin/ssh-agent -D -a $SSH_AUTH_SOCK

              [Install]
              WantedBy=default.target

        - name: Reload systemd user daemon
          command: systemctl --user daemon-reload

    - name: SSH generic config
      blockinfile:
        path: "{{ ansible_user_dir }}/.ssh/config"
        marker: "# {mark} Generic config managed by Ansible"
        block: |
          AddKeysToAgent yes
          ForwardAgent yes
          StrictHostKeyChecking accept-new

- name: Set up editor
  block:
    - name: install neovim
      apt:
        name: neovim
      become: true

    - name: Set editor
      shell: update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 100
      become: true

    - name: Set editor env var
      become: true
      copy:
        content: |
          export EDITOR="/usr/bin/nvim"
        dest: /etc/profile.d/editor.sh

