---
- name: zellij
  block:
    - name: Update toolchain
      command: "rust update stable"

    - name: Install latest Zellij
      community.general.cargo:
        name: zellij
        state: latest
        # executable: "~/.cargo/bin/cargo"
      environment:
        OPENSSL_NO_VENDOR: "1" # force link to system libssl

    - name: Apply theme
      ansible.builtin.lineinfile:
        path: "~/.config/zellij/config.kdl"
        line: theme "catppuccin-latte"
        create: true
