---
- name: zellij
  block:

    - name: Install dependencies
      become: true
      apt:
        name:
          - build-essential
          - pkg-config
          - libssl-dev
          - perl             # For vendoring OpenSSL

    - name: Ensure zellij config directory exists
      ansible.builtin.file:
        path: "~/.config/zellij"
        state: directory

    - name: Settings
      ansible.builtin.copy:
        content: |
          // This file is managed by Ansible.
          // If you'd like to override the default keybindings completely, be sure to change "keybinds" to "keybinds clear-defaults=true"
          keybinds {
              unbind "Ctrl o" // Used for vim
              normal {
                  bind "Ctrl a" { SwitchToMode "Session"; }
              }
              session {
                  bind "Ctrl a" { SwitchToMode "Normal"; }
              }
          }
          theme "iceberg-light"
          show_startup_tips false
        dest: "~/.config/zellij/config.kdl"
        backup: true
        force: true

    - name: Install latest Zellij
      community.general.cargo:
        name: zellij
        state: latest
        executable: "{{ cargo_binary }}"
      environment:
        OPENSSL_NO_VENDOR: "1" # force link to system libssl